[workspace]
resolver = "3"
members = ["bough", "bough-derive", "bough-oracle", "bough-bench"]

[workspace.package]
version = "0.1.0"
authors = ["Zefira Shannon"]
edition = "2024"
rust-version = "1.85"
license = "MPL-2.0"
repository = "https://github.com/bough-frp/bough"

[workspace.dependencies]
bough = { path = "bough", version = "0.1.0" }
bough-derive = { path = "bough-derive", version = "0.1.0" }
bough-oracle = { path = "bough-oracle", version = "0.1.0" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
proptest = { version = "1", default-features = false, features = ["std"] }
critical-section = "1"
criterion = "0.5"
iai-callgrind = "0.14"
